### PR TITLE
Predict batch size default

### PR DESCRIPTION
**Pull request by mheilman**
This changes the default batch size for prediction to be the same as for training, enabling efficient grid search.  Previously `GridSearchCV` would try to make predictions in a single batch, which could take a lot of memory.

This also adds a simple example of using skflow with `GridSearchCV`.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Thanks. @mheilman You have to sign the CLA first and then we can merge.

**Comment by mheilman** [comment]
Yeah, will do.  It might take a day or two for me to get an official OK to sign that.  I'm sure it'll be fine since the CLA seems very reasonable.

**Comment by terrytangyuan** [comment]
Any update on this? @mheilman

**Comment by mheilman** [comment]
Sorry for the delay.  I still don't think this will be a problem, but the person who needs to OK the CLA has been busy.

**Comment by terrytangyuan** [comment]
Sure no worries.

**Comment by terrytangyuan** [comment]
@mheilman skflow has just been moved to TensorFlow [here] (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/skflow). Could you submit a PR there instead? Examples will be located [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/skflow). Thanks!

**Comment by mheilman** [comment]
OK.  By the way, the google CLA website linked above (and [here](https://cla.developers.google.com/clas)) seems to have a bug in it.  It has two buttons for submitting on behalf of only myself or on behalf of my employer, but both forward to the same page.  Is that correct?

**Comment by terrytangyuan** [comment]
Yeah I just noticed that too. I have no idea why. Could you ask TF people when you send a PR there? They may know the right person to take care of this issue.

**Comment by mheilman** [comment]
OK, will do.

**Pull request closed without merging**
